<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dev Env</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.14/require.min.js"></script>
<link rel="stylesheet" href="/static/codemirror/lib/codemirror.css">
<link rel="stylesheet" href="/static/codemirror/theme/colorforth.css">
<style>
html {
    height: 100%;
}
body {
    font-size: 12px;
}
</style>
</head>
<body style="height: 100%; max-height: 100%">
<div class="container-fluid" style="height: 100%; max-height: 100%">
    <div style="height: 100%; width: 50%; float: left" class="panel panel-default">
        <div class="panel-heading">編輯區 - <span id="filename"></span></div>
        <div class="panel-body" style="height: 100%">
            <a href="#" id="save-file-button"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span></a><span id="file-is-changed" style="display:none">(*)</span>
            <textarea id="code" style="width: 100%; height: 100%"></textarea>
        </div>
    </div>
    <div style="height: 100%; width: 50%; float: left">
        <div style="height: 50%; width: 100%" class="panel panel-default">
            <div class="panel-heading">結果區</div>
            <div class="panel-body">
                <textarea id="result-stdout" class="result-text" readonly="readonly" style="background: black; color: white; width: 100%; height:200px"></textarea>
                <textarea id="result-stderr" class="result-text" readonly="readonly" style="background: black; color: white; width: 100%; height:200px; display: none"></textarea>
                <form id="command-form">
                    <ul class="nav nav-pills" style="display: inline-table">
                        <li role="presentation" class="result-switch active" data-type="stdout">
                        <a href="#">
                            stdout
                            <span id="result-stdout-isnew" style="display:none">(*)</span>
                        </a>
                        </li>
                        <li role="presentation" class="result-switch" data-type="stderr">
                        <a href="#">
                            stderr
                            <span id="result-stderr-isnew" style="display:none">(*)</span>
                        </a>
                        </li>
                    </ul>
                    <input type="text" id="command-text">
                    <button type="submit" id="command-button">RUN</button>
                    <button type="button" id="command-stop" style="display: none">STOP</button>
                </form>
            </div>
        </div>
        <div style="height: 50%; width: 100%; max-height: 50%" class="panel panel-default">
            <div class="panel-heading">檔案區 <ol class="breadcrumb" style="display: inline" id="dir-location" data-dir="/"></ol>
        </div>
            <div class="panel-body" id="file-area" style="overflow: scroll; height: 100%">
                <form id="add-folder">
                    <input type="text" id="new-folder-name" placeholder="新資料夾名或檔名">
                    <label><input type="radio" name="type" value="dir" checked="checked"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span></label>
                    <label><input type="radio" name="type" value="file"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></label>
                    <button type="submit"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
                </form>
                <table class="table">
                    <thead>
                        <tr>
                            <td>
                                檔名
                                <a href="#" id="reload-file"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></a>
                            </td>
                            <td>大小</td>
                            <td>時間</td>
                            <td>動作</td>
                        </tr>
                    </thead>
                    <tbody id="file-list">
                    </tbody>
                </table>
        </div>
    </div>
    <div style="clear:both"></div>
</div>
<script>
require.config({
  packages: [{
      name: "codemirror",
      location: "/static/codemirror",
      main: "lib/codemirror"
  }]
});

var update_location_hash = function(){
    var dir_path = $('#filename').data('path');
    var file_path = $('#dir-location').data('dir');

    document.location.hash = dir_path + ';' + file_path;
};

var openfile = function(path){
    if ($('#file-is-changed').is(':visible')) {
        if (!confirm("編輯區檔案尚未儲存，讀取檔案可能會失去變更，您確定要讀取檔案嗎?")) {
            return;
        }
    }
    $('#filename').text(path).data('path', path);
    update_location_hash();
    $.get('/api/getfile?base=' + encodeURIComponent(path), function(ret){
        if (ret.error) {
            alert(ret.message);
            return;
        }
        if (path.match('.php$')) {
            codemirror.setOption('mode', 'php');
        } else if (path.match('.js$')) {
            codemirror.setOption('mode', 'javascript');
        } else if (path.match('.py$')) {
            codemirror.setOption('mode', 'python');
        } else if (path.match('.rb$') || path.match('.json$')) {
            codemirror.setOption('mode', 'ruby');
        } else {
            codemirror.setOption('mode', 'htmlmixed');
        }
        codemirror.setValue(ret.body);
        $('#file-is-changed').hide();
        codemirror.focus();
        $('#code').val(ret.body);
    });
};

var chdir = function(path){
    $('#dir-location').data('dir', path);
    update_location_hash();
    $('#dir-location').html('');
    for (var i = 0; i < path.split('/').length; i ++) {
        if (i == 0) {
            name = 'ROOT';
        } else {
            name = path.split('/')[i];
            if (name.length == 0) {
                continue;
            }
        }
        $('#dir-location').append(
            $('<li></li>').append(
                $('<a></a>').addClass('dir-link').text(name).data('path', path.split('/').slice(0, i).join('/') + '/').attr('href', '#')
            )
        );
    }
    reload_files();
};

var reload_files = function(){
    var base_folder = $('#dir-location').data('dir');
    $.get('/api/listfile?base=' + encodeURIComponent(base_folder), function(ret){
        $('#file-list').html('');
        var files = ret.files.sort(function(a, b){ return (new Date(b.mtime)) - (new Date(a.mtime)); });
        for (var i = 0; i < files.length; i ++) {
            var tr_dom = $('<tr></tr>');
            var a_dom = $('<a></a>').attr('href', '#').addClass(ret.files[i].type + '-link').data('path', ret.files[i].path);
            if (ret.files[i].type == 'dir') {
                a_dom.append('<span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> ');
            } else {
                a_dom.append('<span class="glyphicon glyphicon-file" aria-hidden="true"></span> ');
            }
            a_dom.append($('<span></span>').text(ret.files[i].name));
            tr_dom.append($('<td></td>').append(a_dom));
            tr_dom.append($('<td></td>').append(ret.files[i].size));
            tr_dom.append($('<td></td>').append(ret.files[i].mtime));
            var td_dom = $('<td></td>');
            a_dom = $('<a></a>').attr('href', '#').addClass('delete-file').data('path', ret.files[i].path);
            a_dom.append('<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> ');
            td_dom.append(a_dom);
            if (ret.files[i].type == 'file') {
                a_dom = $('<a></a>').attr('href', '#').addClass('view-file').data('path', ret.files[i].path);
                a_dom.append('<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> ');
                td_dom.append(a_dom);
                a_dom = $('<a></a>').attr('href', '#').addClass('download-file').data('path', ret.files[i].path);
                a_dom.append('<span class="glyphicon glyphicon-download" aria-hidden="true"></span> ');
                td_dom.append(a_dom);
            }

            tr_dom.append(td_dom);
            $('#file-list').append(tr_dom);
        }
    }, 'json');
};

$('#file-area').on('click', '.dir-link', function(e){
    e.preventDefault();
    chdir($(this).data('path'));
}),
$('#file-area').on('click', '.file-link', function(e){
    e.preventDefault();
    openfile($(this).data('path'));
});
$('#file-area').on('click', '.download-file', function(e){
    e.preventDefault();
    var path = $(this).data('path');
    document.location = '/api/getfile?base=' + encodeURIComponent(path) + '&type=download';
});
$('#file-area').on('click', '.view-file', function(e){
    e.preventDefault();
    var path = $(this).data('path');
    window.open('/api/getfile?base=' + encodeURIComponent(path) + '&type=view', '_blank');
});

$('#file-area').on('click', '.delete-file', function(e){
    e.preventDefault();
    var path = $(this).data('path');
    if (!confirm("您確定要刪除 " + path + "?")) {
        return;
    }
    $.post('/api/deletefile?path=' + encodeURIComponent(path), '', function(ret){
        if (ret.error) {
            alert(ret.message);
            return;
        }
        var base_folder = $('#dir-location').data('dir');
        chdir(base_folder);
    }, 'json');
});

$('#save-file-button').click(function(e){
    e.preventDefault();
    var file_path = $('#filename').data('path');
    $.post('/api/savefile?base=' + encodeURIComponent(file_path), 'body=' + encodeURIComponent(codemirror.getValue()), function(ret){
        if (ret.error) {
            alert(ret.message);
            return;
        }
        $('#file-is-changed').hide();
        openfile(file_path);
    }, 'json');
});

$('.result-switch').click(function(e){
    e.preventDefault();
    var type = $(this).data('type');
    $('.result-switch').removeClass('active');
    $(this).addClass('active');
    $('.result-text').hide();
    $('#result-' + type).show();
    $('#result-' + type + '-isnew').hide();

});

var current_session_id = null;

var check_session = function(session_id, stdout_offset, stderr_offset){
    $.get('/api/getsession?session_id=' + encodeURIComponent(session_id) + '&stdout_offset=' + parseInt(stdout_offset) + '&stderr_offset=' + parseInt(stderr_offset), function(ret){
        ['stdout', 'stderr'].map(function(type){
            if (ret[type].length) {
                $('#result-' + type).val($('#result-' + type).val() + ret[type]);
                $('#result-' + type)[0].scrollTop = $('#result-' + type)[0].scrollHeight;
                if (!$('#result-' + type).is(':visible')) {
                    $('#result-' + type + '-isnew').show();
                }
            }
        });

        if (ret.done) {
            $('#command-stop').hide();
            $('#command-button').text('RUN');
            current_session_id = null;
            reload_files();
        } else {
            setTimeout(function(){ check_session(session_id, ret.stdout_offset, ret.stderr_offset); }, 500);
        }
    }, 'json');
};

$('#command-stop').click(function(e){
    e.preventDefault();
    $.post('/api/killsession?session_id=' + encodeURIComponent(current_session_id), '', function(ret){
        // do nothing
    }, 'json');
});

var command_history = [];
var command_position = -1;

$('#command-text').keydown(function(e){
    var code = (e.keyCode ? e.keyCode : e.which);
    if (command_history.length == 0) {
        return;
    }

    if (code == 40) { // down
        if (command_position == -1) {
            return;
        } else if (command_position == command_history.length - 1) {
            command_position = -1;
            $('#command-text').val('');
            return;
        } else {
            command_position ++;
        }
    } else if (code == 38) { // up
        if (command_position == -1) {
            command_position = command_history.length - 1;
        } else if (command_position == 0) {
            return;
        } else {
            command_position --;
        }
    } else {
        return;
    }
    $('#command-text').val(command_history[command_position]);

});

$('#command-form').submit(function(e){
    e.preventDefault();
    var base_folder = $('#dir-location').data('dir');
    $('#command-form').prop('disabled', true);
    if (current_session_id) {
        $.post('/api/senddata?session_id=' + current_session_id, 'data=' + encodeURIComponent($('#command-text').val() + "\n"), function(ret){
            $('#command-form').prop('disabled', false);
            $('#command-text').val('').focus();
        });
    } else {
        if ($('#command-text').val() == '') {
            return;
        }

        if ($('#file-is-changed').is(':visible')) {
            if (!confirm("編輯區檔案尚未儲存，現在執行可能是舊資料，您確定要執行指令嗎?")) {
                return;
            }
        }

        if (command_history[command_history.length - 1] != $('#command-text').val()) {
            command_history.push($('#command-text').val());
            command_position = -1;
        }

        if ('clear' == $('#command-text').val()) {
            $('#command-form').prop('disabled', false);
            $('#command-text').val('').focus();
            $('#result-stderr-isnew').hide();
            $('#result-stdout-isnew').hide();
            $('#result-stderr').val('');
            $('#result-stdout').val('');
            return;
        }

        if ($('#command-text').val().split(' ')[0] == 'cd') {
            $('#command-form').prop('disabled', false);

            var input = $('#command-text').val();
            $('#command-text').val('').focus();
            if (input == 'cd') {
                chdir('/');
                return;
            }
            path = input.split(' ')[1];
            if (!path.match('^/')) {
                path = base_folder + path;
            }
            $.get('/api/listfile?base=' + encodeURIComponent(path), function(ret){
                if (ret.error) {
                    alert(ret.message);
                    return;
                }
                chdir(ret.path);
            }, 'json');
            return;
        }

        if ($('#command-text').val().split(' ')[0] == 'vim') {
            $('#command-form').prop('disabled', false);

            var input = $('#command-text').val();
            $('#command-text').val('').focus();
            path = input.split(' ')[1];
            if (!path.match('^/')) {
                path = base_folder + path;
            }
            $.get('/api/getfile?base=' + encodeURIComponent(path), function(ret){
                if (ret.error) {
                    alert(ret.message);
                    return;
                }
                openfile(ret.path);
            }, 'json');
            return;
        }

        $.post('/api/runcommand?base=' + encodeURIComponent(base_folder) + '&command=' + encodeURIComponent($('#command-text').val()), '', function(ret){
            $('#command-form').prop('disabled', false);
            $('#command-button').text('SEND');
            $('#command-text').val('').focus();
            $('#command-stop').show();
            current_session_id = ret.session_id;
            check_session(ret.session_id, 0, 0);
        }, 'json');
    }
});

$('#reload-file').click(function(e){
    e.preventDefault();
    var base_folder = $('#dir-location').data('dir');
    chdir(base_folder);
});

$('#add-folder').submit(function(e){
    e.preventDefault();
    var base_folder = $('#dir-location').data('dir');
    var new_name = $('#new-folder-name').val();
    var type = $('[name="type"]:checked', this).val();
    $.post('/api/addobject?base=' + encodeURIComponent(base_folder) + '&name=' + encodeURIComponent(new_name) + '&type=' + type, '', function(ret){
        if (ret.error) {
            alert(ret.message);
            return;
        }
        chdir(ret.path);
        $('#new-folder-name').val('');
    }, 'json');
});

var codemirror;
require([
    "codemirror",
    "codemirror/mode/htmlmixed/htmlmixed",
    "codemirror/mode/php/php",
    "codemirror/mode/javascript/javascript",
    "codemirror/mode/python/python",
    "codemirror/mode/ruby/ruby",
], function(CodeMirror) {
    codemirror = CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,
        mode: 'htmlmixed',
    });
    codemirror.setSize('100%', '100%');
    codemirror.setOption('theme', 'colorforth');
    codemirror.on('change', function(){
        if (!$('#file-is-changed').is(':hidden')) {
            return;
        }
        $('#file-is-changed').show();
    });

    $(document).bind('keydown', function(e) {
        if(e.ctrlKey && (e.which == 83)) {
            e.preventDefault();
            $('#save-file-button').click();
            return false;
        }
    });


    if (document.location.hash) {
        var hash = document.location.hash.split('#')[1];
        openfile(hash.split(';')[0]);
        chdir(hash.split(';')[1]);
    } else {
        openfile('/README');
        chdir('/');
    }
});

</script>
</body>
</html>
